<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-11-13 02:24
=======
# Generated by Django 3.1.2 on 2020-11-19 22:34
>>>>>>> 982aac3f94c52ad0fea3ae4ab45c760d8e6e5b53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quoteID', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('quote', models.CharField(max_length=300)),
            ],
        ),
    ]
