<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-11-19 22:34
=======
# Generated by Django 3.1.2 on 2020-12-03 20:24
>>>>>>> bbbff4c1f76d58980e54c0027468121a2ae92828

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('quoteID', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('quote', models.CharField(max_length=300)),
            ],
        ),
    ]
