# Generated by Django 3.1.2 on 2020-11-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='qoute',
            new_name='quote',
        ),
        migrations.RenameField(
            model_name='quotes',
            old_name='qoutesID',
            new_name='quotesID',
        ),
    ]
