# Generated by Django 3.1.2 on 2020-11-12 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='users',
            field=models.ManyToManyField(related_name='skipped_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
