<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-11-13 02:24
=======
# Generated by Django 3.1.2 on 2020-11-19 22:34
>>>>>>> 982aac3f94c52ad0fea3ae4ab45c760d8e6e5b53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='users',
            field=models.ManyToManyField(related_name='skipped_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
