# Generated by Django 3.1.2 on 2020-11-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0002_auto_20201109_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pixelated',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
