# Generated by Django 3.1.2 on 2020-11-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0002_image_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pixelated',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='pixelated/'),
        ),
    ]
