# Generated by Django 3.1.2 on 2020-10-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='userID',
            field=models.CharField(default=1, max_length=16, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
