# Generated by Django 3.1.2 on 2020-10-19 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201005_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
